version: "3"
networks:
  nocobase:
    driver: bridge
services:
  nocobase:
    image: registry.cn-shanghai.aliyuncs.com/nocobase/nocobase:latest
    networks:
      - nocobase
    environment:
      - APP_ENV=${APP_ENV}
      - APP_PORT=${APP_PORT}
      - DB_DIALECT=${DB_DIALECT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_LOGGING=${DB_LOGGING}
    ports:
      - "${APP_PORT}:80"
    restart: always
