version: "3"

networks:
  nocobase:
    driver: bridge

services:
  verdaccio:
    image: verdaccio/verdaccio
    networks:
      - nocobase
    environment:
      VERDACCIO_PORT: ${VERDACCIO_PORT}
    restart: always
    ports:
      - "${VERDACCIO_PORT}:${VERDACCIO_PORT}"

  nocobase:
    image: node:20
    networks:
      - nocobase
    command: >
      bash -c "yarn install && yarn build && yarn start"
    working_dir: /app
    env_file: ./.env
    volumes:
      - ./:/app
    expose:
      - ${APP_PORT}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    restart: unless-stopped
