version: "3"

networks:
  nocobase:
    driver: bridge

services:
  verdaccio:
    image: verdaccio/verdaccio
    networks:
      - nocobase
    environment:
      VERDACCIO_PORT: ${VERDACCIO_PORT}
    restart: always
    ports:
      - "${VERDACCIO_PORT}:${VERDACCIO_PORT}"
    volumes:
      - verdaccio_data:/verdaccio/storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${VERDACCIO_PORT}/"]
      interval: 30s
      timeout: 10s
      retries: 3

  nocobase:
    image: nocobase/nocobase:latest
    networks:
      - nocobase
    env_file: ./.env
    expose:
      - ${APP_PORT}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${APP_PORT}/"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      - NODE_ENV=production
      - APP_PORT=${APP_PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - INIT_ROOT_EMAIL=admin@nocobase.com
      - INIT_ROOT_PASSWORD=admin123
      - INIT_ROOT_NICKNAME=Administrator

volumes:
  verdaccio_data:
